from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field

class DocumentEntity(BaseModel):
    name: str
    value: Any
    confidence: float = 1.0

class DocumentLLMAnalysis(BaseModel):
    """Structured extraction and anomaly assessment from an unstructured document."""
    document_type: str = Field(..., description="Type of document (e.g. claim_form, repair_estimate, invoice, police_report)")
    summary: str = Field(..., description="High-level factual summary of the document contents")
    key_entities: Dict[str, Any] = Field(default_factory=dict, description="Extracted key-value entities such as dates, amounts, VIN, shop name")
    line_items: List[Dict[str, Any]] = Field(default_factory=list, description="Structured line items, parts, or billed services")
    anomalies_detected: List[str] = Field(default_factory=list, description="Factual inconsistencies or abnormalities noticed in document")
    suspicious_indicators: List[str] = Field(default_factory=list, description="Red flags suggesting possible inflation, reuse, or fabrication")
    confidence: float = Field(default=0.95, ge=0.0, le=1.0, description="Extraction confidence score")
    prompt_injection_warning: bool = Field(default=False, description="Whether text contained adversarial prompt override attempts")

class EvidenceCorrelationResult(BaseModel):
    """Cross-evidence factual correlation and discrepancy analysis."""
    cross_evidence_discrepancies: List[str] = Field(default_factory=list, description="Direct factual conflicts between distinct evidence pieces")
    timeline_consistency: str = Field("CONSISTENT", description="Assessment of incident, reporting, and repair timeline")
    severity_vs_reported_damage: str = Field("ALIGNED", description="Correlation between visual damage and billed items")
    suspicious_correlations: List[str] = Field(default_factory=list, description="Correlated patterns across documents, photos, or shops")
    confidence_score: float = Field(default=0.95, ge=0.0, le=1.0)

class InvestigationSynthesisResult(BaseModel):
    """
    Holistic investigation synthesis generated by LLM reasoning over all agent findings.
    Note: The LLM produces qualitative reasoning and investigative summaries;
    the numerical risk score remains strictly determined by the deterministic risk engine.
    """
    executive_summary: str = Field(..., description="Concise, professional multi-agent fraud investigation briefing")
    key_risk_drivers: List[str] = Field(default_factory=list, description="Primary factors contributing to risk or suspicion")
    evidence_synthesis: str = Field(..., description="Detailed narrative correlating documents, photos, rules, and history")
    investigative_recommendations: List[str] = Field(default_factory=list, description="Actionable next steps for the SIU investigator")
    requires_special_investigation: bool = Field(default=False, description="Whether qualitative indicators warrant mandatory SIU deep-dive")
    confidence_assessment: float = Field(default=0.95, ge=0.0, le=1.0)
